#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler"
require "set"

BASE_REF = ENV["GITHUB_BASE_REF"] || "main"

def gem_review_path
  env_path = ENV["GEM_REVIEW_PATH"]
  return env_path if env_path && !env_path.strip.empty?

  repo_root = `git rev-parse --show-toplevel`.strip
  repo_root = Dir.pwd if repo_root.empty?
  File.join(repo_root, "gem_review.md")
end

def fetch_base_lockfile
  # Ensure we have the base branch locally
  system('git', 'fetch', 'origin', BASE_REF, exception: true)

  content = IO.popen(['git', 'show', "origin/#{BASE_REF}:Gemfile.lock"], err: [:child, :out], &:read)
  if content.strip.empty?
    warn "Could not read origin/#{BASE_REF}:Gemfile.lock. Skipping review."
    exit 0
  end
  content
end

def parse_lock(content)
  Bundler::LockfileParser.new(content)
end

def version_tuple(v)
  parts = v.to_s.split(".").map(&:to_i)
  (parts + [0, 0, 0])[0, 3] # ensure [major, minor, patch]
end

def bump_type(old_v, new_v)
  return "added" if old_v.nil?
  return "removed" if new_v.nil?

  o_maj, o_min, o_pat = version_tuple(old_v)
  n_maj, n_min, n_pat = version_tuple(new_v)

  return "major" if n_maj > o_maj
  return "minor" if n_min > o_min
  return "patch" if n_pat > o_pat
  "changed"
end

def risk_level(kind, groups)
  runtime = groups.empty? || (groups & %w[default runtime]).any?
  case kind
  when "major"
    runtime ? "High" : "Medium"
  when "minor"
    runtime ? "Medium" : "Low"
  when "patch"
    "Low"
  else
    "Medium"
  end
end

base_lock_content = fetch_base_lockfile

# Read PR Gemfile.lock from safe path provided by workflow
pr_lockfile_path = ENV["PR_GEMFILE_LOCK_PATH"] || "Gemfile.lock"
begin
  new_lock_content = File.read(pr_lockfile_path)
rescue Errno::ENOENT, Errno::EACCES => e
  warn "Could not read #{pr_lockfile_path}: #{e.message}. Skipping review."
  exit 0
end

base_lock = parse_lock(base_lock_content)
new_lock  = parse_lock(new_lock_content)

base_specs = base_lock.specs.map { |s| [s.name, s.version.to_s] }.to_h
new_specs  = new_lock.specs.map { |s| [s.name, s.version.to_s] }.to_h

base_deps = base_lock.dependencies # name => Bundler::Dependency
new_deps  = new_lock.dependencies

all_gems = Set.new(base_specs.keys) | Set.new(new_specs.keys)

changes = []

all_gems.each do |name|
  old_v = base_specs[name]
  new_v = new_specs[name]
  next if old_v == new_v # unchanged

  kind = bump_type(old_v, new_v)

  # groups from Gemfile (may be nil for transitive deps)
  groups =
    if new_deps[name]
      new_deps[name].groups.map(&:to_s)
    elsif base_deps[name]
      base_deps[name].groups.map(&:to_s)
    else
      [] # purely transitive
    end

  level = risk_level(kind, groups)

  changes << {
    name: name,
    old:  old_v,
    new:  new_v,
    kind: kind,
    groups: (groups.empty? ? ["runtime?"] : groups),
    risk: level
  }
end

if changes.empty?
  begin
    File.write(gem_review_path, "No gem version changes detected between this PR and #{BASE_REF}.")
    unless File.exist?(gem_review_path) && !File.empty?(gem_review_path)
      warn "Failed to write gem_review.md"
      exit 1
    end
    puts "No gem changes."
    exit 0
  rescue StandardError => e
    warn "Error writing gem_review.md: #{e.message}"
    warn "Attempted path: #{gem_review_path}"
    exit 1
  end
end

# Focus the comment on direct deps first, then transitive
# Check if gem is in dependencies (direct) or purely transitive
direct, transitive = changes.partition do |c|
  new_deps[c[:name]] || base_deps[c[:name]]
end

markdown = +"## Dependency change summary\n\n"
markdown << "Base branch: `#{BASE_REF}`\n\n"
markdown << "This PR updates the resolved gem set based on changes in `Gemfile` / `Gemfile.lock` (and related gemspec changes, if any).\n\n"

[["Direct dependencies (from Gemfile)", direct],
 ["Transitive / stdlib gems (from Gemfile.lock only)", transitive]].each do |title, list|
  next if list.empty?

  markdown << "### #{title}\n\n"
  markdown << "| Gem | Old | New | Change | Groups | Risk |\n"
  markdown << "|-----|-----|-----|--------|--------|------|\n"
  list.sort_by { |c| c[:name] }.each do |c|
    markdown << "| `#{c[:name]}` | #{c[:old] || '–'} | #{c[:new] || '–'} | #{c[:kind]} | #{c[:groups].join(', ')} | #{c[:risk]} |\n"
  end
  markdown << "\n"
end

markdown << "_Generated by gem_diff GitHub Action._\n\n"
markdown << "---\n\n"
markdown << "## 🤖 AI-Assisted Fix Instructions\n\n"
markdown << "https://gh.io/copilot-coding-agent-docs \n"
markdown << "@copilot\n\n"
markdown << "Please take full ownership of fixing this Dependabot PR so that **all CI checks pass on this branch**.\n\n"
markdown << "### Goal\n\n"
markdown << "- Analyze this Dependabot PR and the **current CI failures** on this branch.\n"
markdown << "- Make **all necessary code-level changes** (app code, config, assets, migrations, tests, and CI config if needed) so that:\n"
markdown << "  - The same CI workflows that run on this PR **all pass successfully**.\n"
markdown << "- Create a **new pull request that targets this Dependabot branch** with your fixes.\n"
markdown << "- After I merge your PR into this branch, CI on this branch should be **green with no failing jobs**.\n\n"
markdown << "### How I want you to work\n\n"
markdown << "1. **Understand the failures**\n"
markdown << "   - Look at the latest CI runs for this Dependabot branch.\n"
markdown << "   - Identify the exact errors (for example: duplicate migrations, Tailwind build errors, failing tests, etc.).\n\n"
markdown << "2. **Plan and apply fixes**\n"
markdown << "   - Update or remove migrations, schema, views, tests, or CI steps as needed.\n"
markdown << "   - Do **not** downgrade the dependencies; keep the versions from this Dependabot PR and adapt the code/config to them.\n"
markdown << "   - Keep changes minimal and focused only on what's needed to get CI green.\n\n"
markdown << "3. **Run CI yourself in your environment**\n"
markdown << "   - Run the same test commands and workflows locally in your ephemeral environment.\n"
markdown << "   - If they still fail, **iterate on your changes and re-run tests** until they pass or you hit a hard blocker.\n\n"
markdown << "4. **Create the PR to this branch**\n"
markdown << "   - Open a new PR **from your Copilot branch into this Dependabot branch**.\n"
markdown << "   - Include a clear description and commit messages that explain:\n"
markdown << "     - What broke and why.\n"
markdown << "     - Exactly what files you changed and why those changes fix the CI failures.\n\n"
markdown << "5. **Do not stop on the first failure**\n"
markdown << "   - Keep iterating within this session until:\n"
markdown << "     - The tests and CI commands you run are passing, and\n"
markdown << "     - You are confident that merging your PR into this branch will let the GitHub CI checks pass as well.\n\n"
markdown << "**NAME THAT PR AS:** `AI GEM UPGRADE`\n"




begin
  File.write(gem_review_path, markdown)
  unless File.exist?(gem_review_path) && !File.empty?(gem_review_path)
    warn "Failed to write gem_review.md"
    exit 1
  end
  puts markdown
rescue StandardError => e
  warn "Error writing gem_review.md: #{e.message}"
  warn "Attempted path: #{gem_review_path}"
  exit 1
end
